development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] || Settings.redis_url || "redis://localhost:6379/1" %>
  channel_prefix: backend-service_production
